### ISSUE TITLE
Add results relating fold and add

### ISSUE THREAD

**Issue by palmskog** [letouzey/coq-mmaps#12]
We would like to have a lemma relating `fold` and `add`, as is done for FMap [here](https://github.com/VeriNum/vcfloat/blob/4710fb7efbf4cf50e6b1a48101d787907baeb26b/vcfloat/FMap_lemmas.v#L77-L99).

The background for why such a result is useful can be found in section 8 of [this paper](https://github.com/VeriNum/vcfloat/blob/099464dbd680e2dfedd7e6b037631ba6553d5cd6/doc/vcfloat2.pdf).

**Comment by andrew-appel** [comment]
Instead of that link for "this paper", use [this link](https://github.com/VeriNum/vcfloat/blob/099464dbd680e2dfedd7e6b037631ba6553d5cd6/doc/vcfloat2.pdf).  The difference is:  specific commit within the vcfloat repo, so section 8 will still mean the same thing even if the paper is reorganized.

**Comment by palmskog** [comment]
Closing since this issue was addressed by #14 and a corresponding release was done: https://github.com/coq-community/coq-mmaps/releases/tag/v1.1
