### ISSUE TITLE
Release for Coq 8.16

### ISSUE THREAD

**Issue by palmskog** [letouzey/coq-mmaps#5]
Even though the project is WIP, we may want to do a release/tag on GitHub, so that we can have an opam package for regular users as part of the `released` Coq opam repo. Is that OK with you @letouzey? And should we use a "regular" version number 1.0 or something that better signals WIP status?

**Comment by letouzey** [comment]
You have my go for a release.

And I was quickly reviewing my TODO.org file : actually this library is already pretty usable in its current state, so let's call it 1.0. 
Ok, some specs could still be improved, some extra operations could still be added (or modified, less probably). So I will certainly not advertise too much future compatibility. But after all, this has been "stable" (read: stalled) for several years...
